language: python
sudo: false

env:
  - PACKAGE=recomole
  - CODECLIMATE_REPO_TOKEN=124a31e412d7d69cf6b3088405085189a9b98f357f7cb2948327ea9a67a0382b

addons:
  postgresql: "9.4"

before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER lowell WITH PASSWORD 'test';" -U postgres
  - psql -d testing_db -f src/recomole/tests/data/cosim_model.sql
  - psql -d testing_db -f src/recomole/tests/data/metadata.sql
  - psql -d testing_db -f src/recomole/tests/data/relations.sql
  - psql -d testing_db -f src/recomole/tests/data/workid_meta.sql
  - psql -d testing_db -f src/recomole/tests/data/workid_loancount.sql
  - psql -d testing_db -f src/recomole/tests/data/pid_loancount.sql
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

python:
  - "3.5"

# command to install dependencies
install:
  # - pip install -r requirements.txt
  - pip install git+https://github.com/DBCDK/mobus.git
  - pip install git+https://github.com/DBCDK/pytools.git
  - pip install git+https://github.com/DBCDK/pyutils.git
  - pip install pytest-cov
  - pip install codeclimate-test-reporter
  - pip install Sphinx
  - pip install -e .

# command to run tests
script:
  - pytest -s --cov=src/$PACKAGE
  - sphinx-apidoc --force -o docs/source/ src/$PACKAGE `pwd`/src/$PACKAGE/tests/
  - python setup.py build_sphinx --fresh-env --all-files --build-dir docs/build
  - make-build-info
  - python setup.py egg_info --tag-build=".${TRAVIS_BUILD_NUMBER}" bdist_wheel

after_success:
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
  
